add_rules("mode.debug", "mode.release")

set_languages("c++20")
set_warnings("all")
set_targetdir("$(projectdir)/build")

add_requires("asio 1.30.2", "cli11 2.5.0", "openssl", "sqlite3")

target("will-domain")
    set_kind("static")
    add_files("src/domain/**.cpp")
    add_includedirs("src/domain", {public = true})

target("will-protocol")
    set_kind("static")
    add_files("src/infra/protocol/**.cpp")
    add_includedirs("src/infra/protocol", {public = true})
    add_deps("will-domain")

target("will-transport")
    set_kind("static")
    add_files("src/infra/transport/**.cpp")
    add_includedirs("src/infra/transport", {public = true})
    add_defines("ASIO_STANDALONE", {public = true})
    add_packages("asio", {public = true})
    add_syslinks("pthread")
    add_deps("will-protocol")

target("will-persistence")
    set_kind("static")
    add_files("src/infra/persistence/**.cpp")
    add_includedirs("src/infra/persistence", {public = true})
    add_packages("openssl", "sqlite3", {public = true})
    add_deps("will-domain")

target("will-server")
    set_kind("binary")
    add_files("src/server/**.cpp")
    add_includedirs("src/server", "src/server/cli", "src/server/config")
    add_deps("will-transport", "will-persistence")
    add_packages("cli11")

target("will-client")
    set_kind("binary")
    add_files("src/client/**.cpp")
    add_includedirs("src/client", "src/client/cli")
    add_deps("will-transport")
    add_packages("cli11")

target("will-load-clients")
    set_kind("binary")
    add_files("tools/**.cpp", "src/client/clientconfigvalidator.cpp")
    add_includedirs("src/client", "tools", "tools/cli")
    add_defines("ASIO_STANDALONE")
    add_deps("will-protocol")
    add_packages("asio", "cli11")
    add_syslinks("pthread")

includes("tests")
